{% set version = "0.3.10" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: 703caac155dcaad61f78de4cb0666dca778d854dfb90b3699930adee0559a622

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - python-dateutil >=1.0,!=2.0  # [not py3k]
    - python-dateutil >=2.0  # [py3k]

test:
  imports:
    - freezegun

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Let your Python tests travel through time.'

extra:
  recipe-maintainers:
    - ocefpaf
