{% set version = "0.3.14" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: 6262de2f4bab671f7189bb8a0b9d8751da69a53f0b9813fb8f412681662d872a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - python-dateutil >2.0

test:
  imports:
    - freezegun

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Let your Python tests travel through time'

extra:
  recipe-maintainers:
    - ocefpaf
