{% set version = "1.5.5" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: ac7742a6cc6c25a2c35e9292dfd554b897b517d2dec26891a2e8debf205cb94a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil >=2.7

test:
  imports:
    - freezegun
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Let your Python tests travel through time
  description: |
    FreezeGun is a library that allows your Python tests to
    travel through time by mocking the datetime module.
  dev_url: https://github.com/spulec/freezegun
  doc_url: https://github.com/spulec/freezegun

extra:
  recipe-maintainers:
    - ocefpaf
