{% set version = "0.3.15" %}

package:
  name: freezegun
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: e2062f2c7f95cc276a834c22f1a17179467176b624cc6f936e8bc3be5535ad1b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - python-dateutil >2.0

test:
  imports:
    - freezegun

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Let your Python tests travel through time'

extra:
  recipe-maintainers:
    - ocefpaf
