travis:
  secure:
    BINSTAR_TOKEN: pXeocCyK8lwwUE54TgRURQAJW/3MtP6EwlJdHuqBHRlDDiJOuUm5fYfa0M4LlhEYXPRAvjJrOHyTOsW+BjcfmGLN2HdkBgnJ4WbZNhIxNAGnUB3HocM8z+O2ICPWuQeAuXTIa7OyI8naEOt5KcVIXO6jpCs63YQhYg7o+QvY0HOwKvMEK70ODGYjMuZ1za2fcTBC6qaHk03RANp+i/xbv2g9pTnioHkPWU5JLkmLWpjaajCiElk3NvLIJqZsErCFBtDvjWY+sovCBoOg5lOGy2guDifUVLHrhEAoCiiv8ol8SnOkGPZ/4OkLnW77kVf5d0ZAEACH/aCte3ny3mW/8c2LwOE4y+WnrVquRNKW172Emtb01GozJUrGEQ3983+8vLGfDfzOtBDM1GcZmydaM5MLlG9J/vG4aIXIO013RtIHaOBfi0+3wynG4wPf/bFRh2Diez4lchuNApP5vkrX23WYwq8C4Bkp7CwIPi1FvWzznDf+ae7FK+C+tmV7OSmMdk8HhBmN9kxZ9d6xbjWwRiREr65EUjmEXMBDDCHxRj6Nxljkvy7Y7UOCLo85gVVlMc+VuLzUzY5lgaAjKWGvgDp2nRnYsPIJ5oUbrJD2EM5t7iOnKNgXl7ZOr9ae9qnWCvrChou/dculy2G6+/91VoB31ZAAA2qmXDqWYqDprRE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
