travis:
  secure:
    BINSTAR_TOKEN: tXYCOf5+QEcOHsgTc2vxulo4HbmQ1Ooq9Ymf3UNnzx7KHIaq+YBRCvbiduzTeTtDNqKTzJxPxNTgywnTn2jHW3aHy2GzmFNfjq0uX2SoMPRTfYf6i5Ba9LnZ9SM0kZ75s+qQ9qntIMHMdWVTi9a88kp/bNrfbjVu1jsD8x3vrgWkjZ+Ke3FKWeNMBRNb+9utn4Rx1qZX72nbJ8WhpHB3/dFrwY9c9mcrbIATD6nltc+1vOUPzITWYUmPc62W1UFmEgy187TjDqMGotC2X5jC20RGof4CpAi2l0GKARydIt1dePplp6fK2iLkDZ/nndvXyPHiJX9hoA+ZJ7n4on0MMMBISgFm8yRUFf5esSnkaUYWt6YrxBxR13MjywG/RT272cnOetsXwpsyFycD+GsI+X4vy/2KtE32XlKCr4l+ySmV4z3Za5lwU8y44ZZlQmLcXfWT1E0+DAE5OIiQALRwn8mkQBZyZArAa8X+keV+ZNTsRBr0lPRPxvW6f/n4nWUJcmXN7/rasn66hPJjK9mIu3fVnIc1fR4oHe348V+eGtngY2ZvafALkKI8ndrsHNhd0R0Y98nr3GZ11q+epI1v/4fAAROtmCpA/9p9FqeytrCzCdqUqOL6m5TsmvBLEBBIImFD38LmFMU41sqDhuhalnCS4E5dlpQZoTENVdKrAns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
