travis:
  secure:
    BINSTAR_TOKEN: B9cHK1aPxehHekqVP3MH+u6kS8LzuAmBOI9oKRXoNZ3cFWT+OiiNYJj5k9jmoZKq3UGaqvpHlSt8ewFH5JqbT7FNsaxmGHCoFXNpY0VeY2r4DBphmFwjT9EbvtfS2eHW6qgZ2aiF4c+Dro06NWKkrZ2fnTmCKFF0aP/lNpJn8EgYdJZyWURbijyKVmoB7HaQleFMgzO7f4gxkzwMKYigOP26iwwJRAKaRGTglIuTx4+g4+FGKQR5WNxeoiAfAiXJSSSy62jgzLe0Lii/ClKqfh55+gtDGxp/n/n2q40fdnMQug8zpEK6cbX2FABXgyWxrsGPYwAXUEZN6GpEIZtCmBSJQu2DrcKL+vMR+fymadT0TIRNsYpM2JLjXQ49GBhmWXPkAD6I0UzEpV+pXI5J1yCU8rQZqd8gkX0qTaDJ6UpEk61JSDqwzYMlyqZnjFglQMm9mMU1YZDS69f/h46+z328K0tDswiFRUf2SSD2zShrpuDfMeSelU6aWgNO8gkv3bx9SzHsX/Gg6H2esBDSD7uzo0ZMBqUz7ZZPjtCvKtw6urMqpxDPnPqO3AwuGJHo7pBZNtGHVDuBJ6UU4MFC+g+ipbPE5Lnfgd6QR84IMynUhe/7UBRi0DEatnHt1rtaBLeD1NLRpEYbA6Mo15k4QTvLQzpDmdrrKEk7047i9uc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
